queue_rules:
  - name: default
    conditions:
      # Conditions to get out of the queue (= merged)
      - check-success=Finish Test
pull_request_rules:
  - name: merge PRs labeled ready-to-merge
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - status-success=Node 10 Tests
      - status-success=Node 12 Tests
      - base=dev
    actions:
      queue:
        method: squash
        name: default
  - name: delete head branch on merged pull requests
    conditions:
      - merged
      - -head~=^(master|dev)$
      - -author~=^dependabot(|-preview)\[bot\]$
    actions:
      label:
        remove:
          - ready-to-merge
      delete_head_branch:
