name: Check for required label
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
  label:
    types: ['*']

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say 
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: No Filter
        id: check1
        uses: ./
        with:
          github_secret: ${{ secrets.github_token }}
      - name: No Filter
        id: check2
        uses: ./
        with:
          github_secret: ${{ secrets.github_token }}
          filter: testlabel,bug,enhancement